[package]
name = "spspf-template"
version = "0.1.0"
edition = "2021"

[dependencies]
psp = { path = "../../rust-psp/psp" }
spspf = { path = "../../", features = ["graphics"] }

[profile.release]
debug = true
